blocksstate: main.cpp blocksstate.cpp mino.hpp mino_utils.hpp timekeeper.hpp
	g++ -O2 -std=c++17 -o blocksstate main.cpp

blocksstate_alt: main.cpp blocksstate.cpp mino.hpp mino_utils.hpp timekeeper.hpp
	g++ -O2 -std=c++17 -DMYGAME_ALT_PROFILE -o blocksstate_alt main.cpp

blocksstate_chokudai: main_chokudai.cpp blocksstate.cpp mino.hpp mino_utils.hpp timekeeper.hpp
	g++ -O2 -std=c++17 -o blocksstate_chokudai main_chokudai.cpp
